spring.application.name=evouchers-api

spring.profiles.include=core-default

spring.profiles.group.dev=core-dev
spring.profiles.group.staging=core-staging
spring.profiles.group.prod=core-prod

server.servlet.context-path=/evouchers-api