
app.voucher.responsible.title=Le pr\u00e9sident
app.voucher.responsible.name=John Doe
app.voucher.responsible.signature-path=classpath:assets/sgn/signature-mock.svg

app.voucher.facturX.name=Amicale des sapeurs pompiers de La Verrie
app.voucher.facturX.address=6 rue Denis Papin - La Verrie
app.voucher.facturX.zip-code=85130
app.voucher.facturX.city=CHANVERRIE
app.voucher.facturX.country-code=FR

app.signing.keystore.path=classpath:/keystores/dummy-keystore.p12
app.signing.keystore.password=changeit
app.signing.keystore.default-kid=default

