
spring.config.import=optional:secret.properties

#metadata

#app.voucher.responsible.title=
#app.voucher.responsible.name=
#app.voucher.responsible.signature-path=

app.voucher.facturX.name=Amicale des sapeurs pompiers de La Verrie
app.voucher.facturX.address=6 rue Denis Papin - La Verrie
app.voucher.facturX.zip-code=85130
app.voucher.facturX.city=CHANVERRIE
app.voucher.facturX.country-code=FR

#app.signing.keystore.path=
#app.signing.keystore.default-kid=
#app.signing.keystore.password=